# Generated by Django 6.0.3 on 2026-03-23 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Default Address', max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='building_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Building Type'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Default City', max_length=255, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='Default Name', max_length=255, verbose_name='Customer Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='0000000000', max_length=255, verbose_name='Customer Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pin_code',
            field=models.CharField(default='0000', max_length=255, verbose_name='Pin Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Default State', max_length=255, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_qty',
            field=models.IntegerField(default=0, verbose_name='Total Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(verbose_name='Total Price'),
        ),
    ]
